version: '3'

services:
  db:
    image: postgres
    env_file:
      .env
  redis:
    image: "redis:alpine"
  django:
    build: .
    command: ["python", "manage.py", "runserver"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  celery:
    build: .
    command: celery -A development worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  frontend:
    build: ../../react-work/a-bit-of-habit-react/react-project
    command: ["npm", "start"]
    volumes:
      - .:/app/frontend
      - .:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: