# Generated by Django 3.2.6 on 2021-08-26 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habituser',
            old_name='date_started',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='level',
        ),
        migrations.RemoveField(
            model_name='achievementuser',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='habituser',
            name='achievement_level',
        ),
        migrations.RemoveField(
            model_name='habituser',
            name='checked_date',
        ),
        migrations.RemoveField(
            model_name='habituser',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='achievement',
            name='amount_to_reach',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='achievementuser',
            name='achievement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.achievement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievementuser',
            name='description',
            field=models.TextField(default='', verbose_name='achievement description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habituser',
            name='days_checked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(choices=[('WOODEN', 'WOODEN'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM')], max_length=30, verbose_name='achievement name'),
        ),
        migrations.AlterField(
            model_name='achievementuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='comment text'),
        ),
    ]
