# Generated by Django 3.2.6 on 2021-12-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habituser',
            name='start_date',
        ),
    ]
