# Generated by Django 3.2.6 on 2021-08-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210826_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
